# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool: Default
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'PaglaSC'
    backendAzureRmOverrideSubscriptionID: 'bc304d74-dfec-4f01-af8f-f598f6619edb'
    backendAzureRmResourceGroupName: 'rg-paglabackend'
    backendAzureRmStorageAccountName: 'paglabackend'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
